config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  devise_for :users, path: "users", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    get "login", to: "users/sessions#new"
    get "register", to: "users/registrations#new"
  end

  resource :appsumo, only: [:show, :create]

  devise_for :admin_users, path: "admin_users"

  resource :dashboard, only: [:show]
  resources :custom_domains do
    get :setup_dns
  end
  resources :links
  resource :support, only: [:new, :create]
  resource :account, only: [:show, :update]
  resource :billing, only: [:show] do
    get :waiting

    resource :redeem, only: [:new, :create]
  end
  resources :api_keys, only: [:index, :create, :edit, :update] do
    post :reactivate
    post :deactivate
  end
  resource :settings, only: [:show]
  resource :export_links, only: [:new]
  resource :redeem, only: [:create]
  resources :deactivated_users, only: [:destroy]

  resource :qrcode, only: [] do
    get :download
  end

  # For removal
  resource :bio, only: [:show]
  resource :user_attributes, only: [:update]
  resources :public_profile_links, only: [:create, :destroy]
  resources :public_profile, only: [:show, :update]

  authenticated :user do |user|
    root to: "dashboards#show", as: :authenticated_root
  end

  root to: "marketing#index"
  get "/terms", to: "marketing#terms"
  get "/privacy", to: "marketing#privacy"

  authenticate :admin_user do |user|
    mount Sidekiq::Web => "/sidekiq"
    root to: "admin/links#index", as: :authenticated_admin_root
  end

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :links, only: [:index]
    resources :custom_domains, only: [:index]
    resources :users, only: [:index, :destroy] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
    resources :link_visits, only: [:index]
    resources :coupons, only: [:index, :new] do
      collection do
        post :import
      end
    end
    resources :plans, only: [:index, :show, :edit, :update]
  end
  get "/admin", to: "admin/dashboards#show"

  # API endpoints
  namespace :api do
    namespace :v1 do
      post "/shorten", to: "links#create"
      resources :links, only: [:create]
      resources :shortmenu, only: [:create]
    end
  end

  # Custom errors
  get "/404", to: "errors#not_found", via: :all
  get "/422", to: "errors#unacceptable", via: :all
  get "/500", to: "errors#internal_error", via: :all

  # This must be the last route in the file
  get "/:slug", to: "redirect_links#new", as: :redirect
end

app/controllers/appsumos_controller.rb
class AppsumosController < ApplicationController
  skip_authorization_check
  before_action :check_if_logged_in?
  before_action :check_for_valid_coupon, only: [:create]

  layout "auth"

  def show
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    coupon = Coupon.find_by(code: coupon_params[:coupon])

    if @user.save
      Appsumo::Redeem.(@user, coupon)
      sign_in(@user)
    else
      render :show
    end
  end

  private

  def check_if_logged_in?
    return unless current_user

    redirect_to dashboard_path
  end

  def check_for_valid_coupon
    unless Coupon.find_by(code: params[:user][:coupon])
      flash[:error] = "Invalid code. Please check again."
      redirect_to appsumo_path
    end

    @coupon = Coupon.find_by(code: params[:user][:coupon])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def coupon_params
    params.require(:user).permit(:coupon)
  end
end

app/views/appsumos/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-5 col-xl-4 my-5">
      <div class="text-center">
        <img src="/appsumo_btfy.png" class="img-fluid" />
      </div>
      
      <h1 class="display-4 text-center mb-3">
        Sign up
      </h1>

      <p class="text-muted text-center mb-5">
        Access your dashboard.
      </p>
      
      <%= form_with model: @user, url: appsumo_path, local: true do |f| %>
        <%= render(FormNotificationComponent.new(model: @user)) %>

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: "form-control", placeholder: "username" %>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email Address" %>
          <%= f.email_field :email, class: "form-control",
            placeholder: "name@address.com" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control",
            placeholder: "Enter your password" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control",
            placeholder: "Confirm your password" %>
        </div>

        <div class="form-group">
          <%= f.label :coupon %>
          <%= f.text_field :coupon, class: "form-control", placeholder: "Enter coupon code" %>
        </div>

        <%= f.submit "Sign up", class: "btn btn-lg btn-block btn-primary mb-3" %>
        <small class="text-muted">By creating an account, you agree to the our
          <%= link_to "Terms of Service", terms_path %> and
          <%= link_to "Privacy Policy", privacy_path %>.
        </small>

        <hr class="my-4">

        <div class="text-center">
          <small class="text-muted text-center">
            Already have an account? <%= link_to "Sign in", new_session_path("user") %>.
          </small>
        </div>
      <% end %>
    </div>
  </div>
</div>